# Generated by Django 3.0.7 on 2020-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subscribed', models.BooleanField(default=True)),
                ('subscribedwhen', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-subscribedwhen',),
            },
        ),
    ]
