# Generated by Django 3.0.7 on 2020-07-06 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('recipientemail', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
                ('shared', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='core.Post')),
            ],
            options={
                'ordering': ('-shared',),
            },
        ),
    ]
