# Generated by Django 3.0.7 on 2020-07-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sharepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharePost',
            new_name='SharedPost',
        ),
    ]
