# Generated by Django 3.0.7 on 2020-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200706_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpost',
            name='sent',
            field=models.BooleanField(default=True),
        ),
    ]
