# Generated by Django 3.0.7 on 2020-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200707_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banners'),
        ),
    ]
