# Generated by Django 3.0.7 on 2020-07-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_pic', models.ImageField(max_length=255, upload_to='avatar')),
                ('profile_pic', models.ImageField(max_length=255, upload_to='profile')),
                ('name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=25)),
                ('caption', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('resume_pdf', models.FileField(upload_to='resume')),
            ],
        ),
    ]
