# Generated by Django 3.0.7 on 2020-07-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='suggested',
        ),
    ]
