# Generated by Django 3.0.7 on 2020-07-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_contactme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactme',
            name='phone_number',
        ),
    ]
