# Generated by Django 3.0.7 on 2020-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200708_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactme',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
