# Generated by Django 3.0.7 on 2020-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='testimonies'),
        ),
    ]
