# Generated by Django 3.0.7 on 2020-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_testimonial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='caption',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
