# Generated by Django 3.0.7 on 2020-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200710_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimony',
            field=models.TextField(max_length=150),
        ),
    ]
